# Generated by Django 4.2.4 on 2023-08-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('Steve Jobs', 'Steve Jobs')], max_length=15)),
                ('content', models.TextField()),
            ],
        ),
    ]
