# Generated by Django 4.2.4 on 2023-08-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steve_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
